### ISSUE TITLE
Add support for third-party custom subscription types with `apply_filters`

### ISSUE THREAD

**Issue by hesyifei** [TheStanfordDaily/tsd-push-notification#6]
Currently, we do not support any custom subscription types other than `location_ids`.

For `location_ids`, we call the function provided by [TSD Locations](https://github.com/TheStanfordDaily/stanforddaily-website/tree/8dc66de5ffc50a88642b99578eec38c6bd7d2056/wp-content/plugins/tsd-locations):
https://github.com/TheStanfordDaily/tsd-push-notification/blob/a3663601f32923616daeaab8252fdfe5f1edf109/inc/auto-send-subscription.php#L44-L53
https://github.com/TheStanfordDaily/tsd-push-notification/blob/a3663601f32923616daeaab8252fdfe5f1edf109/inc/helper.php#L2-L4

However, it would be better if we could let other plugins add any custom subscription type with `apply_filters`. For example, TSD Locations should be able to `add_filter` to `$notification_receiver_ids` and `tsd_pn_get_subscription_types()`.

**Comment by epicfaace** [comment]
@hesyifei great, can we document this? Otherwise we'll probably forget the filter names
